name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Build extension
      run: cargo build --verbose --features extension
    - name: Run tests
      run: cargo test --verbose --features extension

  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Rustfmt
      run: cargo fmt --check
